In [3]:
import tensorflow as tf

In [6]:
arr1=tf.constant([5,3,3,4,3])
arr2=tf.constant([6,4,3,5,6])
result = tf.global_variables_initializer()
with tf.Session() as session:
    session.run(result)
    print(session.run(arr1))
with tf.Session() as session:
    session.run(result)
    print(session.run(arr2))

[ 5.  3.  3.  4.  3.]
[ 6.  4.  3.  5.  6.]


In [9]:
a = tf.add(arr1,arr2,)
with tf.Session() as sess:
    print(sess.run(a))

[ 11.   7.   6.   9.   9.]


In [18]:
mean1=tf.reduce_mean(arr1)
with tf.Session() as sess:
    print(sess.run(mean1))
mean2=tf.reduce_mean(arr2)
with tf.Session() as sess:
    print(sess.run(mean2))


3.6
4.8


In [19]:
##calculating the variance for x: variance(x) = sum((x-mean(x))2)
rhs=tf.subtract(arr1,mean1)
with tf.Session() as sess:
    print(sess.run(rhs))


[ 1.4000001 -0.5999999 -0.5999999  0.4000001 -0.5999999]


In [42]:
##squaring the values of array and calculating variance
squared_rhs= tf.square(rhs)
var_x = tf.reduce_mean(squared_rhs)
with tf.Session() as sess:
    print(sess.run(var_x))




0.64


In [41]:
##calculating the covariance of x and y
farr1=tf.subtract(arr1,mean1)
with tf.Session() as sess:
    print(sess.run(farr1))
farr2=tf.subtract(arr2,mean1)
with tf.Session() as sess:
    print(sess.run(farr2))
mul_arrays = tf.multiply(farr1,farr2)
with tf.Session() as sess:
    print(sess.run(mul_arrays))
cov = tf.reduce_mean(mul_arrays)
with tf.Session() as sess:
    print(sess.run(cov))



[ 1.4000001 -0.5999999 -0.5999999  0.4000001 -0.5999999]
[ 2.4000001  0.4000001 -0.5999999  1.4000001  2.4000001]
[ 3.36000037 -0.24000002  0.3599999   0.56000018 -1.43999982]
0.52


In [45]:
##calculating m
m = tf.divide(cov,var_x)
with tf.Session() as sess:
    print(sess.run(m))

0.8125


In [52]:
##calculating c
inter_c = tf.multiply(mean1,m)
c= tf.subtract(mean2,inter_c)
with tf.Session() as sess:
    print(sess.run(c))

1.875
